
import React, { useState, useEffect, useMemo, useCallback, Suspense, lazy } from 'react';
import { Transaction, Page, BalanceSummary, FixedExpense, MonthlyReport } from './types';
import { Icons, CATEGORIES } from './constants';
import { formatCurrency } from './utils/formatters';

// Componentes Leves (Importação Estática)
import Sidebar from './components/Sidebar';
import TransactionModal from './components/TransactionModal';

// Componentes de Página Pesados (Importação Dinâmica / Lazy Loading)
const Dashboard = lazy(() => import('./components/Dashboard'));
const TransactionsList = lazy(() => import('./components/TransactionsList'));
const Insights = lazy(() => import('./components/Insights'));
const FixedExpensesManager = lazy(() => import('./components/FixedExpensesManager'));
const History = lazy(() => import('./components/History'));
const AnnualSummary = lazy(() => import('./components/AnnualSummary'));

const INITIAL_TRANSACTIONS: Transaction[] = [
  { id: '1', description: 'Salário Mensal', amount: 5000, date: new Date().toISOString(), type: 'income', category: 'Salário' },
  { id: '2', description: 'Aluguel', amount: 1500, date: new Date().toISOString(), type: 'expense', category: 'Moradia' },
];

const PageLoader = () => (
  <div className="flex-1 flex flex-col items-center justify-center min-h-[400px] animate-in fade-in duration-500">
    <div className="w-12 h-12 border-4 border-accent/20 border-t-accent rounded-full animate-spin mb-4"></div>
    <p className="text-gray-400 font-black text-[10px] uppercase tracking-[0.2em]">Otimizando visualização...</p>
  </div>
);

export default function App() {
  const [currentPage, setCurrentPage] = useState<Page>(Page.Dashboard);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [isSplashVisible, setIsSplashVisible] = useState(true);
  
  const [editingTransaction, setEditingTransaction] = useState<Transaction | null>(null);
  const [showAutoToast, setShowAutoToast] = useState(false);
  const [autoCount, setAutoCount] = useState(0);

  const [transactions, setTransactions] = useState<Transaction[]>(() => {
    try {
      const saved = localStorage.getItem('family_transactions');
      return saved ? JSON.parse(saved) : INITIAL_TRANSACTIONS;
    } catch { return INITIAL_TRANSACTIONS; }
  });

  const [fixedExpenses, setFixedExpenses] = useState<FixedExpense[]>(() => {
    try {
      const saved = localStorage.getItem('family_fixed_expenses');
      return saved ? JSON.parse(saved) : [];
    } catch { return []; }
  });

  const [history, setHistory] = useState<MonthlyReport[]>(() => {
    try {
      const saved = localStorage.getItem('family_history');
      return saved ? JSON.parse(saved) : [];
    } catch { return []; }
  });

  const [monthlyGoal, setMonthlyGoal] = useState<number>(() => {
    const saved = localStorage.getItem('family_monthly_goal');
    return saved ? parseFloat(saved) : 0;
  });

  useEffect(() => {
    localStorage.setItem('family_transactions', JSON.stringify(transactions));
    localStorage.setItem('family_fixed_expenses', JSON.stringify(fixedExpenses));
    localStorage.setItem('family_history', JSON.stringify(history));
    localStorage.setItem('family_monthly_goal', monthlyGoal.toString());
  }, [transactions, fixedExpenses, history, monthlyGoal]);

  const processRecurringExpenses = useCallback(() => {
    const now = new Date();
    const currentMonthKey = `${now.getFullYear()}-${now.getMonth() + 1}`;
    
    setTransactions(prev => {
      const newTransactions: Transaction[] = [];
      fixedExpenses.forEach(exp => {
        const id = `auto-${exp.id}-${currentMonthKey}`;
        // Só adiciona se o ID único para este mês ainda não existir
        if (!prev.some(t => t.id === id)) {
          const expenseDate = new Date(now.getFullYear(), now.getMonth(), exp.dayOfMonth);
          newTransactions.push({
            id,
            description: `[FIXO] ${exp.description}`,
            amount: exp.amount,
            date: expenseDate.toISOString(),
            type: 'expense',
            category: exp.category,
            isAutoGenerated: true
          });
        }
      });

      if (newTransactions.length > 0) {
        setAutoCount(newTransactions.length);
        setShowAutoToast(true);
        setTimeout(() => setShowAutoToast(false), 6000);
        return [...newTransactions, ...prev];
      }
      return prev;
    });
  }, [fixedExpenses]);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsSplashVisible(false);
      processRecurringExpenses();
    }, 1800);
    return () => clearTimeout(timer);
  }, []); // Executa apenas no mount para evitar loops, o processamento real é engatado pelo fixedExpenses em callbacks específicos se necessário

  // Re-processa quando as despesas fixas mudam (caso o usuário adicione uma nova mid-month)
  useEffect(() => {
    if (!isSplashVisible) {
      processRecurringExpenses();
    }
  }, [fixedExpenses, isSplashVisible, processRecurringExpenses]);

  const summary: BalanceSummary = useMemo(() => {
    return transactions.reduce((acc, curr) => {
      if (curr.type === 'income') {
        acc.totalIncome += curr.amount;
        acc.totalBalance += curr.amount;
      } else {
        acc.totalExpense += curr.amount;
        acc.totalBalance -= curr.amount;
      }
      return acc;
    }, { totalBalance: 0, totalIncome: 0, totalExpense: 0 });
  }, [transactions]);

  const handleSaveTransaction = (txData: Omit<Transaction, 'id'> & { id?: string }) => {
    if (txData.id) {
      setTransactions(prev => prev.map(t => t.id === txData.id ? { ...txData, id: txData.id! } : t));
    } else {
      const tx: Transaction = { ...txData, id: Math.random().toString(36).substr(2, 9) };
      setTransactions(prev => [tx, ...prev]);
    }
    setIsModalOpen(false);
    setEditingTransaction(null);
  };

  const openEditModal = (tx: Transaction) => {
    setEditingTransaction(tx);
    setIsModalOpen(true);
  };

  const handleAddFixedExpense = (newExp: Omit<FixedExpense, 'id'>) => {
    const exp: FixedExpense = { ...newExp, id: Math.random().toString(36).substr(2, 9) };
    setFixedExpenses(prev => [...prev, exp]);
  };

  const handleDeleteFixedExpense = (id: string) => {
    setFixedExpenses(prev => prev.filter(e => e.id !== id));
  };

  const handleDeleteTransaction = (id: string) => {
    setTransactions(prev => prev.filter(t => t.id !== id));
  };

  const handleSaveMonthlyReport = () => {
    const now = new Date();
    const currentYear = now.getFullYear();
    const currentMonth = now.getMonth();
    const monthKey = `${currentYear}-${currentMonth + 1}`;
    
    const monthTransactions = transactions.filter(t => {
      const d = new Date(t.date);
      return d.getFullYear() === currentYear && d.getMonth() === currentMonth;
    });

    if (monthTransactions.length === 0) {
      alert("Não há transações registradas no mês atual para arquivar.");
      return;
    }

    if (history.some(h => h.monthKey === monthKey)) {
      if (!confirm("Já existe um relatório salvo para este mês. Deseja substituí-lo?")) return;
      setHistory(prev => prev.filter(h => h.monthKey !== monthKey));
    }

    const monthSummary = monthTransactions.reduce((acc, curr) => {
      if (curr.type === 'income') {
        acc.income += curr.amount;
        acc.balance += curr.amount;
      } else {
        acc.expense += curr.amount;
        acc.balance -= curr.amount;
      }
      return acc;
    }, { income: 0, expense: 0, balance: 0 });

    const expenses = monthTransactions.filter(t => t.type === 'expense');
    const grouped = expenses.reduce<Record<string, number>>((acc, curr) => {
      acc[curr.category] = (acc[curr.category] || 0) + curr.amount;
      return acc;
    }, {});
    
    const topCategory = (Object.entries(grouped) as [string, number][])
      .sort((a, b) => b[1] - a[1])[0]?.[0] || 'Nenhum';

    const monthName = new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(now);
    
    const report: MonthlyReport = {
      id: Math.random().toString(36).substr(2, 9),
      monthKey,
      monthName: monthName.charAt(0).toUpperCase() + monthName.slice(1),
      totalIncome: monthSummary.income,
      totalExpense: monthSummary.expense,
      balance: monthSummary.balance,
      topCategory,
      saveDate: now.toISOString()
    };

    setHistory(prev => [report, ...prev]);
    alert("Relatório do mês arquivado com sucesso!");
  };

  const exportData = () => {
    const data = { transactions, fixedExpenses, history, monthlyGoal, exportDate: new Date().toISOString() };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `family-gestor-backup-${new Date().toISOString().split('T')[0]}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const data = JSON.parse(event.target?.result as string);
        if (data.transactions) {
          if (confirm('A restauração irá substituir todos os seus dados atuais. Continuar?')) {
            setTransactions(data.transactions);
            setFixedExpenses(data.fixedExpenses || []);
            setHistory(data.history || []);
            setMonthlyGoal(data.monthlyGoal || 0);
            alert('Dados restaurados com sucesso!');
          }
        }
      } catch { alert('Erro ao processar o arquivo.'); }
    };
    reader.readAsText(file);
    e.target.value = '';
  };

  if (isSplashVisible) {
    return (
      <div className="fixed inset-0 bg-secondary flex flex-col items-center justify-center z-50 transition-opacity duration-500">
        <div className="bg-white p-12 rounded-[3rem] shadow-2xl border border-gray-100 max-w-md w-full flex flex-col items-center text-center animate-in zoom-in-95 duration-700">
           <div className="w-20 h-20 bg-primary rounded-[1.5rem] flex items-center justify-center mb-8 shadow-xl shadow-primary/20">
              <svg width="40" height="40" viewBox="0 0 52 50" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M24.1469 15.4746L14.971 30.2038C14.7818 30.5188 14.6817 30.8759 14.6807 31.2397C14.6796 31.6035 14.7776 31.9612 14.965 32.2772C15.1523 32.5933 15.4225 32.8566 15.7485 33.0411C16.0746 33.2256 16.4452 33.3248 16.8235 33.3288H35.1752C35.5535 33.3248 35.9241 33.2256 36.2502 33.0411C36.5762 32.8566 36.8464 32.5933 37.0337 32.2772C37.2211 31.9612 37.3191 31.6035 37.318 31.2397C37.317 30.8759 37.2169 30.5188 37.0277 30.2038L27.8519 15.4746C27.6587 15.1684 27.3868 14.9153 27.0623 14.7397C26.7378 14.564 26.3717 14.4717 25.9994 14.4717C25.627 14.4717 25.2609 14.4717 24.9364 14.7397C24.6119 14.9153 24.34 15.1684 24.1469 15.4746Z" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
           </div>
           <h2 className="text-2xl font-black text-primary mb-2 tracking-tight">Family Gestor</h2>
           <p className="text-gray-400 text-sm font-bold uppercase tracking-widest">Sincronizando seus dados...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-screen overflow-hidden bg-secondary">
      <Sidebar 
        currentPage={currentPage} 
        setCurrentPage={setCurrentPage} 
        isOpen={isSidebarOpen}
        setIsOpen={setIsSidebarOpen}
      />
      
      <main className="flex-1 overflow-y-auto custom-scrollbar p-4 md:p-8 relative">
        <header className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-2xl font-black text-primary tracking-tight">
              {currentPage === Page.Dashboard && 'Dashboard'}
              {currentPage === Page.Transactions && 'Transações'}
              {currentPage === Page.Recurring && 'Gastos Fixos'}
              {currentPage === Page.History && 'Histórico Mensal'}
              {currentPage === Page.Annual && 'Resumo Anual'}
              {currentPage === Page.Insights && 'Insights de IA'}
              {currentPage === Page.Settings && 'Configurações'}
            </h1>
            <p className="text-gray-400 text-xs font-bold uppercase tracking-widest mt-1">
              {currentPage === Page.History ? 'Análise retrospectiva oficial' : 
               currentPage === Page.Annual ? 'Consolidação de desempenho anual' :
               'Gestão Financeira Inteligente'}
            </p>
          </div>
          
          <div className="flex gap-3">
            {currentPage === Page.Dashboard && (
              <button 
                onClick={handleSaveMonthlyReport}
                className="flex items-center gap-2 bg-white text-primary border border-gray-100 px-5 py-2.5 rounded-2xl hover:bg-gray-50 transition-all shadow-sm font-black text-[10px] uppercase tracking-widest active:scale-95"
              >
                <Icons.History />
                <span className="hidden sm:inline">Arquivar Mês</span>
              </button>
            )}
            <button 
              onClick={() => { setEditingTransaction(null); setIsModalOpen(true); }}
              className="flex items-center gap-2 bg-accent text-white px-6 py-2.5 rounded-2xl hover:bg-blue-700 transition-all shadow-xl shadow-accent/20 font-black text-[10px] uppercase tracking-widest active:scale-95"
            >
              <Icons.Plus />
              <span className="hidden sm:inline">Nova Transação</span>
            </button>
          </div>
        </header>

        <div className="max-w-7xl mx-auto space-y-6">
          <Suspense fallback={<PageLoader />}>
            {currentPage === Page.Dashboard && (
              <Dashboard 
                transactions={transactions} 
                fixedExpenses={fixedExpenses} 
                summary={summary} 
                monthlyGoal={monthlyGoal}
                onUpdateGoal={setMonthlyGoal}
                onDelete={handleDeleteTransaction}
                onEdit={openEditModal}
                onAddDirect={handleSaveTransaction}
              />
            )}
            {currentPage === Page.Transactions && (
              <TransactionsList 
                transactions={transactions} 
                onDelete={handleDeleteTransaction}
                onEdit={openEditModal}
              />
            )}
            {currentPage === Page.Recurring && (
              <FixedExpensesManager 
                fixedExpenses={fixedExpenses} 
                onAdd={handleAddFixedExpense} 
                onDelete={handleDeleteFixedExpense} 
              />
            )}
            {currentPage === Page.History && (
              <History 
                history={history} 
                fixedExpenses={fixedExpenses}
                onDeleteReport={(id) => {
                   if(confirm("Deseja excluir este registro histórico?")) {
                     setHistory(prev => prev.filter(h => h.id !== id));
                   }
                }} 
              />
            )}
            {currentPage === Page.Annual && (
              <AnnualSummary history={history} />
            )}
            {currentPage === Page.Insights && (
              <Insights transactions={transactions} />
            )}
            {currentPage === Page.Settings && (
              <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-12">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                  <div className="bg-white p-10 rounded-[2.5rem] border border-gray-100 shadow-sm flex flex-col justify-between group">
                    <div>
                      <h3 className="text-xl font-black text-primary tracking-tight mb-2">Segurança de Dados</h3>
                      <p className="text-sm text-gray-400 mb-8">Exporte um backup completo para manter seus dados seguros fora do navegador.</p>
                    </div>
                    <button onClick={exportData} className="w-full flex items-center justify-center gap-3 bg-primary text-white py-5 rounded-2xl font-black text-xs uppercase tracking-[0.2em] hover:bg-gray-800 transition-all shadow-xl shadow-gray-200 active:scale-[0.98]">
                      <Icons.Download /> Gerar Backup JSON
                    </button>
                  </div>
                  <div className="bg-white p-10 rounded-[2.5rem] border border-gray-100 shadow-sm">
                    <h3 className="text-xl font-black text-primary tracking-tight mb-2">Importação</h3>
                    <p className="text-sm text-gray-400 mb-8">Restaure transações e histórico a partir de um arquivo anterior.</p>
                    <div className="relative group">
                      <input type="file" accept=".json" onChange={handleFileUpload} className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10" />
                      <div className="border-2 border-dashed border-gray-100 rounded-[1.75rem] py-10 px-8 flex flex-col items-center justify-center text-center transition-all group-hover:border-accent group-hover:bg-accent/5">
                        <div className="w-12 h-12 bg-accent/10 text-accent rounded-2xl flex items-center justify-center mb-4">
                          <Icons.Upload />
                        </div>
                        <p className="text-[10px] font-black text-primary uppercase tracking-widest">Clique ou arraste o backup</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="bg-white rounded-[2.5rem] p-10 border border-red-50 shadow-sm text-center">
                  <h2 className="text-lg font-black text-primary tracking-tight mb-4">Gerenciamento do Sistema</h2>
                  <p className="text-xs text-gray-400 mb-6 uppercase font-bold tracking-widest">Zona de Perigo</p>
                  <button 
                    onClick={() => {
                      if(confirm('ATENÇÃO: Isso apagará TODOS os seus dados permanentemente. Continuar?')) {
                        localStorage.clear();
                        window.location.reload();
                      }
                    }}
                    className="px-12 py-4 text-red-500 border-2 border-red-100 rounded-2xl font-black text-[10px] uppercase tracking-widest hover:bg-red-50 transition-all active:scale-95"
                  >
                    Resetar Aplicativo Completo
                  </button>
                </div>
              </div>
            )}
          </Suspense>
        </div>
      </main>

      <TransactionModal 
        isOpen={isModalOpen} 
        onClose={() => { setIsModalOpen(false); setEditingTransaction(null); }} 
        onAdd={handleSaveTransaction}
        editingTransaction={editingTransaction}
      />

      {showAutoToast && (
        <div className="fixed bottom-8 right-8 z-[100] animate-in slide-in-from-right-full duration-500">
          <div className="bg-white border border-gray-100 shadow-2xl rounded-[1.5rem] p-5 flex items-center gap-5 max-w-sm border-l-4 border-l-accent">
            <div className="w-12 h-12 bg-accent/10 text-accent rounded-full flex items-center justify-center shrink-0">
              <Icons.Recurring />
            </div>
            <div>
              <h4 className="font-black text-primary text-sm tracking-tight">Novos lançamentos fixos!</h4>
              <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest">Processamos <strong>{autoCount}</strong> despesas recorrentes.</p>
            </div>
            <button onClick={() => setShowAutoToast(false)} className="text-gray-300 hover:text-gray-500 p-2">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
