
export type TransactionType = 'income' | 'expense';

export interface Transaction {
  id: string;
  description: string;
  amount: number;
  date: string;
  type: TransactionType;
  category: string;
  observations?: string;
  isAutoGenerated?: boolean;
}

export interface FixedExpense {
  id: string;
  description: string;
  amount: number;
  category: string;
  dayOfMonth: number;
}

export interface MonthlyReport {
  id: string;
  monthName: string; // Ex: "Maio de 2024"
  monthKey: string;  // Ex: "2024-05"
  totalIncome: number;
  totalExpense: number;
  balance: number;
  topCategory: string;
  saveDate: string;
}

export interface BalanceSummary {
  totalBalance: number;
  totalIncome: number;
  totalExpense: number;
}

export enum Page {
  Dashboard = 'dashboard',
  Transactions = 'transactions',
  Insights = 'insights',
  Recurring = 'recurring',
  History = 'history',
  Annual = 'annual',
  Settings = 'settings'
}
